# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
# Import data into pandas from CSV to Panda
cities_df = pd.read_csv('../output_data/cities.csv',  index_col=0)
cities_df.tail(3)

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
City_ID,,,,,,,,,
568,bubaque,37,GW,1592331133,86,11.28,-15.83,27.38,7.24
569,coquimbo,75,CL,1592331133,71,-29.95,-71.34,14.00,4.10
570,manuk mangkaw,34,PH,1592331133,71,4.80,119.85,28.96,2.88

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)
fig = gmaps.figure(zoom_level=2,center=[20, 20])

In [5]:
locations = cities_df[['Lat', 'Lng']]
weights = cities_df['Humidity']

In [6]:
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [10]:
vacation_df = cities_df
vacation_df = vacation_df[(vacation_df["Max Temp"] >= 28) & (vacation_df["Max Temp"] <= 35)]
vacation_df = vacation_df[(vacation_df["Wind Speed"] > 1)& (vacation_df["Wind Speed"] < 5)]
vacation_df = vacation_df[(vacation_df["Cloudiness"] < 20)]
vacation_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
City_ID,,,,,,,,,
57,houma,1,US,1592330963,58,29.60,-90.72,32.22,2.60
64,hithadhoo,0,MV,1592331049,76,-0.60,73.08,29.25,4.29
96,carutapera,6,BR,1592330983,76,-1.20,-46.02,29.18,2.85
157,eirunepe,10,BR,1592330823,47,-6.66,-69.87,32.68,1.89
187,cururupu,7,BR,1592331071,58,-1.83,-44.87,30.76,3.25
203,kudahuvadhoo,1,MV,1592331075,76,2.67,72.89,28.93,3.45
255,dalbandin,6,PK,1592331086,10,28.89,64.41,32.72,2.60
261,obidos,15,BR,1592331065,70,-1.92,-55.52,29.49,2.81
296,pundaguitan,2,PH,1592331093,71,6.37,126.17,28.37,1.47
316,nuevo progreso,15,MX,1592331097,59,23.17,-97.95,31.67,3.13
337,hit,0,IQ,1592330975,13,33.64,42.83,32.77,4.59
353,aripuana,0,BR,1592331102,39,-9.17,-60.63,33.25,1.66
365,dakar,0,SN,1592331096,79,14.69,-17.44,29.00,4.10
434,bossier city,1,US,1592330959,52,32.52,-93.73,33.33,2.10
435,formosa do rio preto,0,BR,1592331116,41,-11.05,-45.19,28.93,4.41
481,itacoatiara,18,BR,1592331122,74,-3.14,-58.44,29.00,1.50
515,jaru,2,BR,1592331127,62,-10.44,-62.47,30.18,1.01
532,abu dhabi,18,AE,1592330894,59,24.47,54.37,34.00,2.10

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [11]:
hotel1_df = vacation_df
hotel1_df['Hotel Name'] = ""
hotel1_df.reset_index(drop=True, inplace=True)
hotel1_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
0,houma,1,US,1592330963,58,29.60,-90.72,32.22,2.60,
1,hithadhoo,0,MV,1592331049,76,-0.60,73.08,29.25,4.29,
2,carutapera,6,BR,1592330983,76,-1.20,-46.02,29.18,2.85,
3,eirunepe,10,BR,1592330823,47,-6.66,-69.87,32.68,1.89,
4,cururupu,7,BR,1592331071,58,-1.83,-44.87,30.76,3.25,
5,kudahuvadhoo,1,MV,1592331075,76,2.67,72.89,28.93,3.45,
6,dalbandin,6,PK,1592331086,10,28.89,64.41,32.72,2.60,
7,obidos,15,BR,1592331065,70,-1.92,-55.52,29.49,2.81,
8,pundaguitan,2,PH,1592331093,71,6.37,126.17,28.37,1.47,
9,nuevo progreso,15,MX,1592331097,59,23.17,-97.95,31.67,3.13,
10,hit,0,IQ,1592330975,13,33.64,42.83,32.77,4.59,
11,aripuana,0,BR,1592331102,39,-9.17,-60.63,33.25,1.66,
12,dakar,0,SN,1592331096,79,14.69,-17.44,29.00,4.10,
13,bossier city,1,US,1592330959,52,32.52,-93.73,33.33,2.10,
14,formosa do rio preto,0,BR,1592331116,41,-11.05,-45.19,28.93,4.41,
15,itacoatiara,18,BR,1592331122,74,-3.14,-58.44,29.00,1.50,
16,jaru,2,BR,1592331127,62,-10.44,-62.47,30.18,1.01,
17,abu dhabi,18,AE,1592330894,59,24.47,54.37,34.00,2.10,

In [12]:
# find the closest hotel of each city

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = { 
    "radius": 5000,
    "type": "hotel",
    "keyword":"bed-breakfast",
    "key": g_key               }

for i in range(0,len(hotel1_df)):    
    city = hotel1_df.iloc[i,0]
    lat = hotel1_df.iloc[i,5]                  #get location
    lng = hotel1_df.iloc[i,6]
    params['location'] = f"{lat},{lng}"       # add location to params dict
    
    response = requests.get(base_url, params=params).json()   # assemble url and make API request
    results = response['results']                             # extract results (results is a dict in googleapi)
    #print(response)
    
    if response['status'] == 'OK':                           # Result is not []     
        print(f"Hotel in {city} is {results[0]['name']}.")
        hotel1_df.iloc[i,9] = results[0]['name']          # add to the column
    
    else :
        print(f"NO HOTEL IN {city}.")

Hotel in houma is Grand Bayou Noir.
Hotel in hithadhoo is MY FINE STAY.
Hotel in carutapera is Pousada Sol.
NO HOTEL IN eirunepe.
Hotel in cururupu is Pousada Través'cia.
Hotel in kudahuvadhoo is Fima Guest House.
NO HOTEL IN dalbandin.
Hotel in obidos is Pousada Paraíso.
NO HOTEL IN pundaguitan.
NO HOTEL IN nuevo progreso.
NO HOTEL IN hit.
NO HOTEL IN aripuana.
Hotel in dakar is Maison Augustin Ly.
Hotel in bossier city is Fairfield Place Bed and Breakfast.
Hotel in formosa do rio preto is Pousada e Borracharia Bahia.
Hotel in itacoatiara is Rudijane Hotel.
Hotel in jaru is Hotel Marques.
Hotel in abu dhabi is Beach Rotana.

In [13]:
hotel1_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
0,houma,1,US,1592330963,58,29.60,-90.72,32.22,2.60,Grand Bayou Noir
1,hithadhoo,0,MV,1592331049,76,-0.60,73.08,29.25,4.29,MY FINE STAY
2,carutapera,6,BR,1592330983,76,-1.20,-46.02,29.18,2.85,Pousada Sol
3,eirunepe,10,BR,1592330823,47,-6.66,-69.87,32.68,1.89,
4,cururupu,7,BR,1592331071,58,-1.83,-44.87,30.76,3.25,Pousada Través'cia
5,kudahuvadhoo,1,MV,1592331075,76,2.67,72.89,28.93,3.45,Fima Guest House
6,dalbandin,6,PK,1592331086,10,28.89,64.41,32.72,2.60,
7,obidos,15,BR,1592331065,70,-1.92,-55.52,29.49,2.81,Pousada Paraíso
8,pundaguitan,2,PH,1592331093,71,6.37,126.17,28.37,1.47,
9,nuevo progreso,15,MX,1592331097,59,23.17,-97.95,31.67,3.13,
10,hit,0,IQ,1592330975,13,33.64,42.83,32.77,4.59,
11,aripuana,0,BR,1592331102,39,-9.17,-60.63,33.25,1.66,
12,dakar,0,SN,1592331096,79,14.69,-17.44,29.00,4.10,Maison Augustin Ly
13,bossier city,1,US,1592330959,52,32.52,-93.73,33.33,2.10,Fairfield Place Bed and Breakfast
14,formosa do rio preto,0,BR,1592331116,41,-11.05,-45.19,28.93,4.41,Pousada e Borracharia Bahia
15,itacoatiara,18,BR,1592331122,74,-3.14,-58.44,29.00,1.50,Rudijane Hotel
16,jaru,2,BR,1592331127,62,-10.44,-62.47,30.18,1.01,Hotel Marques
17,abu dhabi,18,AE,1592330894,59,24.47,54.37,34.00,2.10,Beach Rotana

In [14]:
hotel_df = hotel1_df[hotel1_df['Hotel Name'] != '']
hotel_df = hotel_df.drop(["Cloudiness","Date","Humidity","Max Temp","Wind Speed"], axis=1)
hotel_df

,City,Country,Lat,Lng,Hotel Name
0,houma,US,29.60,-90.72,Grand Bayou Noir
1,hithadhoo,MV,-0.60,73.08,MY FINE STAY
2,carutapera,BR,-1.20,-46.02,Pousada Sol
4,cururupu,BR,-1.83,-44.87,Pousada Través'cia
5,kudahuvadhoo,MV,2.67,72.89,Fima Guest House
7,obidos,BR,-1.92,-55.52,Pousada Paraíso
12,dakar,SN,14.69,-17.44,Maison Augustin Ly
13,bossier city,US,32.52,-93.73,Fairfield Place Bed and Breakfast
14,formosa do rio preto,BR,-11.05,-45.19,Pousada e Borracharia Bahia
15,itacoatiara,BR,-3.14,-58.44,Rudijane Hotel
16,jaru,BR,-10.44,-62.47,Hotel Marques
17,abu dhabi,AE,24.47,54.37,Beach Rotana

In [15]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [16]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations,info_box_content=hotel_info)

# Display figure
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))